name: Block Develop to Release
on:
  pull_request:
    branches: [release]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block develop branch
        run: |
          if [ "${{ github.head_ref }}" = "develop" ]; then
            echo "❌ Merging from 'develop' to 'release' is prohibited"
            exit 1
          else
            echo "✅ Merge from '${{ github.head_ref }}' to 'release' is allowed"
          fi
